RefugioAnimal/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    logout_then_login,
    PasswordResetView,  PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)
from django.urls import path,include
# from apps.mascota.views import indexMascota

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  LoginView.as_view(template_name='login.html'), name='login'),
    path('accounts/login/',  LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', logout_then_login, name='logout'),
    path('adopcion/', include('apps.adopcion.urls', namespace='adopcion')),
    path('mascota/',  include('apps.mascota.urls', namespace='mascota')),
    path('usuario/',  include('apps.usuario.urls', namespace='usuario')),
    path(
        'reset/password_reset',
        PasswordResetView.as_view(),
        {
            'template_name':'tpass_recovery/passwd_reset_form.html',
            'email_template_name':'tpass_recovery/passwd_reset_email.html'
        },
        name='password_reset'
    ),
    path(
        'reset/password_reset_done',
        PasswordResetDoneView.as_view(),
        {'template_name':'tpass_recovery/passwd_reset_done.html'},
        name='password_reset_done'
    ),
    path(
        'reset/password_reset_confirm/<slug:uidb64>/<slug:token>/',
        PasswordResetConfirmView.as_view(),
        {'template_name':'tpass_recovery/passwd_reset_confirm.html'},
        name='password_reset_confirm'
    ),
    path(
        'reset/password_reset_complete',
        PasswordResetCompleteView.as_view(),
        {'template_name':'tpass_recovery/passwd_reset_complete.html'},
        name='password_reset_complete'
    )
]

apps/mascota/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from apps.mascota.views import (
    indexMascota,
    # mascotaNueva,
    # listarMascotas,
    # mascotaEditar,
    # mascotaEliminar,
    MascotaList,
    MascotaCreate,
    MascotaUpdate,
    MascotaDelete,
    WSMascotaList
)

app_name = 'mascota'

urlpatterns = [
    path('', indexMascota, name='mascota_index'),
    path('nueva',   login_required(MascotaCreate.as_view()), name='mascota_nueva'),
    path('listar', login_required(MascotaList.as_view()), name='listar_mascotas'),
    path('editar/<int:pk>',  login_required(MascotaUpdate.as_view()), name='editar_mascota'),
    path('eliminar/<int:pk>',  login_required(MascotaDelete.as_view()), name='eliminar_mascota'),
    path('ws/all', WSMascotaList, name='ws_all')
]

apps/mascota/models.py
from django.db import models

from apps.adopcion.models import Persona

class Vacuna(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self,):
        return self.nombre

class Mascota(models.Model):
    # folio   = models.CharField(max_length=10, primary_key=True)
    nombre  = models.CharField(max_length=50)
    sexo    = models.CharField(max_length=10)
    edad    = models.IntegerField()
    fecha_rescate = models.DateField()
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    vacuna  = models.ManyToManyField(Vacuna, blank=True)
    

apps/mascota/forms.py
from django import forms

from apps.mascota.models import Mascota,Vacuna

class MascotaForm(forms.ModelForm):

    class Meta:
        model = Mascota

        fields = [
            'nombre',
            'sexo',
            'edad',
            'fecha_rescate',
            'persona',
            'vacuna'
        ]

        labels = {
            'nombre'        : 'Nombre',
            'sexo'          : 'Sexo',
            'edad'          : 'Edad aproximada',
            'fecha_rescate' : 'Fecha de Rescate',
            'persona'       : 'Adoptante',
            'vacuna'        : 'Vacunas'
        }

        widgets = {
            'nombre'        : forms.TextInput(attrs={'class':'form-control'}),
            'sexo'          : forms.TextInput(attrs={'class':'form-control'}),
            'edad'          : forms.TextInput(attrs={'class':'form-control'}),
            'fecha_rescate' : forms.DateTimeInput(format='%Y-%m-%d'),
            'persona'       : forms.Select(attrs={'class':'form-control'}),
            'vacuna'        : forms.CheckboxSelectMultiple()
        }
    # vacuna = forms.ModelMultipleChoiceField(queryset=Vacuna.objects.all())

apps/mascota/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.core import serializers
from django.views.generic import (
    ListView, CreateView, UpdateView, DeleteView
)

from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota


def WSMascotaList(request):
    return HttpResponse(
        serializers.serialize(
            'json',
            Mascota.objects.all(),
            fields=['nombre','sexo','edad']
        ),
        content_type='application/json'
    )

def indexMascota(request):
    return render(request, 'tmascota/index.html')

def mascotaNueva(request):
    print('method received: {}'.format(request.method))
    if request.method != 'POST':
        form = MascotaForm()
    else:
        form = MascotaForm(request.POST)

        print('Reading form, is_valid: {}'.format(form.is_valid()))
        if form.is_valid():
            form.save()
            print('redirect to index mascota')
            return redirect('mascota:listar_mascotas')

    return render(request, 'tmascota/mascota_form.html', {'form':form})

def listarMascotas(request):
    all_mascotas = Mascota.objects.all()
    return render(request, 'tmascota/mascota_list.html', {'mascotas':all_mascotas})

def mascotaEditar(request, id_mascota):
    try:
        objmascota  = Mascota.objects.get(id=id_mascota)
    except Mascota.DoesNotExist:
        print('Mascota no encontrada con id: {}'.format(id_mascota))
        return redirect('mascota:listar_mascotas')
        
    if request.method == 'GET':
        form = MascotaForm(instance=objmascota)
    else:
        form = MascotaForm(request.POST, instance=objmascota)
        if form.is_valid():
            form.save()
            return redirect('mascota:listar_mascotas')
    
    return render(request, 'tmascota/mascota_form.html', {'form':form})

def mascotaEliminar(request, id_mascota):
    try:
        objmascota  = Mascota.objects.get(id=id_mascota)
    except Mascota.DoesNotExist:
        print('Mascota no encontrada con id: {}'.format(id_mascota))
        return redirect('mascota:listar_mascotas')
        
    if request.method == 'POST':
        objmascota.delete()
        return redirect('mascota:listar_mascotas')
    
    return render(request, 'tmascota/mascota_delete.html', {'mascota':objmascota})

class MascotaModel:
    model = Mascota

class MascotaList(MascotaModel, ListView):
    template_name = 'tmascota/mascota_list.html'
    paginate_by = 2

class MascotaCRUD(MascotaModel):
    form_class    = MascotaForm
    template_name = 'tmascota/mascota_form.html'
    success_url   = reverse_lazy('mascota:listar_mascotas')

class MascotaCreate(MascotaCRUD, CreateView):
    pass

class MascotaUpdate(MascotaCRUD, UpdateView):
    pass

class MascotaDelete(DeleteView):
    model = Mascota
    template_name =  'tmascota/mascota_delete.html'
    success_url   = reverse_lazy('mascota:listar_mascotas')

templates/tmascota/index.html
{% extends 'tbases/base.html' %}

{% block title %} App mascota {% endblock %}

{% block header %}
{# <h5>Header app mascota custom</h5> #}
{% include 'tbases/header.html' %}
{% endblock %}

{% block content %}
<h1>Este es el bloque del contenido mascota custom</h1>
{% endblock %}

templates/tmascota/mascota_delete.html
{% extends 'tbases/base.html' %}


{% block content %}
<form method="post">
	{% csrf_token %}

	<h3>¿Estas seguro de eliminar {{ object.nombre }}?</h3>

	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class="btn btn-default" href="{% url 'mascota:listar_mascotas' %}">Cancelar</a>
</form>
{% endblock %}

templates/tmascota/mascota_form.html
{% extends 'tbases/base.html' %}


{% block content %}
<form method="post">
	{% csrf_token %}
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{ form.nombre.name }}">{{ form.nombre.label }}</label>
				{{ form.nombre }}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{ form.sexo.name }}">{{ form.sexo.label }}</label>
				{{ form.sexo }}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{ form.edad.name }}">{{ form.edad.label }}</label>
				{{ form.edad }}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{ form.fecha_rescate.name }}">{{ form.fecha_rescate.label }}</label>
				{{ form.fecha_rescate }}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{ form.persona.name }}">{{ form.persona.label }}</label>
				{{ form.persona }}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{ form.vacuna.name }}">{{ form.vacuna.label }}</label>
				{{ form.vacuna }}
			</div>
		</div>
	</div>
	<button type="submit">Guardar</button>
</form>
{% endblock %}

templates/tmascota/mascota_list.html
{% extends 'tbases/base.html' %}

{% block content %}
<table class="table table-bordered">
	<tread>
		<tr>
			<td>#</td>
			<td>Nombre</td>
			<td>Sexo</td>
			<td>Edad</td>
			<td>Fecha Rescate</td>
			<td>Adoptante</td>

		</tr>
	</tread>
	<tbody>
		{% if object_list %}
			{% for each_mascota in object_list %}
				<tr>
					<td>{{ each_mascota.id }}</td>
					<td>{{ each_mascota.nombre }}</td>
					<td>{{ each_mascota.sexo }}</td>
					<td>{{ each_mascota.edad }}</td>
					<td>{{ each_mascota.fecha_rescate }}</td>
					<td>{{ each_mascota.persona.nombre }} {{each_mascota.persona.apellidos}}</td>
					<td>
						<a class="btn btn-primary" href="{% url 'mascota:editar_mascota' each_mascota.id %}">Editar</a>
					</td>
					<td>
						<a class="btn btn-danger" href="{% url 'mascota:eliminar_mascota' each_mascota.id %}">borrar</a>
					</td>
				</tr>
			{% endfor %}
		{% else %}
			<h1>No existen registro de mascotas</h1>
		{% endif %}
		
	</tbody>
</table>
<ul class="pager">
	{% if page_obj.has_previous %}
		<li>
			<a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
		</li>
	{% endif %}
	{% if page_obj.has_next %}
		<li>
			<a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
		</li>
	{% endif %}
</ul>
{% endblock %}