RefugioAnimal/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    logout_then_login,
    PasswordResetView,  PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)
from django.urls import path,include
# from apps.mascota.views import indexMascota

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  LoginView.as_view(template_name='login.html'), name='login'),
    path('accounts/login/',  LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', logout_then_login, name='logout'),
    path('adopcion/', include('apps.adopcion.urls', namespace='adopcion')),
    path('mascota/',  include('apps.mascota.urls', namespace='mascota')),
    path('usuario/',  include('apps.usuario.urls', namespace='usuario')),
    path(
        'reset/password_reset',
        PasswordResetView.as_view(),
        {
            'template_name':'tpass_recovery/passwd_reset_form.html',
            'email_template_name':'tpass_recovery/passwd_reset_email.html'
        },
        name='password_reset'
    ),
    path(
        'reset/password_reset_done',
        PasswordResetDoneView.as_view(),
        {'template_name':'tpass_recovery/passwd_reset_done.html'},
        name='password_reset_done'
    ),
    path(
        'reset/password_reset_confirm/<slug:uidb64>/<slug:token>/',
        PasswordResetConfirmView.as_view(),
        {'template_name':'tpass_recovery/passwd_reset_confirm.html'},
        name='password_reset_confirm'
    ),
    path(
        'reset/password_reset_complete',
        PasswordResetCompleteView.as_view(),
        {'template_name':'tpass_recovery/passwd_reset_complete.html'},
        name='password_reset_complete'
    )
]

apps/adopcion/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from apps.adopcion.views import index_adopcion

from apps.adopcion import views

app_name = 'adopcion'

urlpatterns = [
    path('', login_required(views.index_adopcion)),
    path('solicitud', login_required(views.SolicitudCreate.as_view()), name='solicitud'),
    path('solicitud/listar', login_required(views.SolicitudList.as_view()), name='listar_solicitud'),
    path('solicitud/editar/<int:pk>', login_required(views.SolicitudUpdate.as_view()), name='editar_solicitud'),
    path('solicitud/eliminar/<int:pk>', login_required(views.SolicitudDelete.as_view()), name='eliminar_solicitud')
]

templates/tadopcion/solicitud_delete.html
{% extends 'tbases/base.html' %}


{% block content %}
<form method="post">
	{% csrf_token %}

	<h3>¿Estas seguro de eliminar {{ object.persona.nombre }} {{ object.persona.apellidos }}?</h3>

	<button class="btn btn-danger" type="submit">Sí, eliminar</button>
	<a class="btn btn-default" href="{% url 'adopcion:listar_solicitud' %}">Cancelar</a>
</form>
{% endblock %}

templates/tadopcion/solicitud_form.html
{% extends "tbases/base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ frm_persona.nombre.name }}">{{ frm_persona.nombre.label }}</label>
                {{ frm_persona.nombre }}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ frm_persona.apellidos.name }}">{{ frm_persona.apellidos.label }}</label>
                {{ frm_persona.apellidos }}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ frm_persona.edad.name }}">{{ frm_persona.edad.label }}</label>
                {{ frm_persona.edad }}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ frm_persona.telefono.name }}">{{ frm_persona.telefono.label }}</label>
                {{ frm_persona.telefono }}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ frm_persona.email.name }}">{{ frm_persona.email.label }}</label>
                {{ frm_persona.email }}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ frm_persona.domicilio.name }}">{{ frm_persona.domicilio.label }}</label>
                {{ frm_persona.domicilio }}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form.numero_mascotas.name }}">{{ form.numero_mascotas.label }}</label>
                {{ form.numero_mascotas }}
            </div>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <div class="form-group">
                <label for="{{ form.razones.name }}">{{ form.razones.label }}</label>
                {{ form.razones }}
            </div>
        </div>
    </div>
    <div class="col-md-8 col-md-offset-2">
        <div class="form-group">
            <button class="btn btn-primary" type="submit">Guardar</button>
        </div>
    </div>
</form>
{% endblock %}

templates/tadopcion/solicitud_listar.html
{% extends "tbases/base.html" %}

{% block  content %}
<table class="table table-bordered">
    <thead>
        <tr>
            <td>No Solicitud</td>
            <td>Adoptante</td>
            <td>No Mascota</td>
            <td>Razones</td>
            {% comment %} <td>Acciones</td> {% endcomment %}
        </tr>
    </thead>
    <tbody>
        {% if object_list %}
            {% for solicitud in object_list %}
                <tr>
                    <td> {{ solicitud.id }} </td>
                    <td> {{ solicitud.persona.nombre }} </td>
                    <td> {{ solicitud.numero_mascotas }} </td>
                    <td> {{ solicitud.razones }} </td>
                    <td>
                        <a href="{% url 'adopcion:editar_solicitud' solicitud.id %}" class="btn btn-primary">Editar</a>
                    </td>
                    <td>
                        <a href="{% url 'adopcion:eliminar_solicitud' solicitud.id %}" class="btn btn-danger">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <h1>No hay registros de solicitudes</h1>
        {% endif %}
    </tbody>
</table>
{% endblock %}