RefugioAnimal/urls.py
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    logout_then_login,
    PasswordResetView,  PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)
from django.urls import path,include
# from apps.mascota.views import indexMascota

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',  LoginView.as_view(template_name='login.html'), name='login'),
    path('accounts/login/',  LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', logout_then_login, name='logout'),
    path('adopcion/', include('apps.adopcion.urls', namespace='adopcion')),
    path('mascota/',  include('apps.mascota.urls', namespace='mascota')),
    path('usuario/',  include('apps.usuario.urls', namespace='usuario')),
    path(
        'reset/password_reset',
        PasswordResetView.as_view(),
        {
            'template_name':'tpass_recovery/passwd_reset_form.html',
            'email_template_name':'tpass_recovery/passwd_reset_email.html'
        },
        name='password_reset'
    ),
    path(
        'reset/password_reset_done',
        PasswordResetDoneView.as_view(),
        {'template_name':'tpass_recovery/passwd_reset_done.html'},
        name='password_reset_done'
    ),
    path(
        'reset/password_reset_confirm/<slug:uidb64>/<slug:token>/',
        PasswordResetConfirmView.as_view(),
        {'template_name':'tpass_recovery/passwd_reset_confirm.html'},
        name='password_reset_confirm'
    ),
    path(
        'reset/password_reset_complete',
        PasswordResetCompleteView.as_view(),
        {'template_name':'tpass_recovery/passwd_reset_complete.html'},
        name='password_reset_complete'
    )
]

apps/adopcion/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from apps.adopcion.views import index_adopcion

from apps.adopcion import views

app_name = 'adopcion'

urlpatterns = [
    path('', login_required(views.index_adopcion)),
    path('solicitud', login_required(views.SolicitudCreate.as_view()), name='solicitud'),
    path('solicitud/listar', login_required(views.SolicitudList.as_view()), name='listar_solicitud'),
    path('solicitud/editar/<int:pk>', login_required(views.SolicitudUpdate.as_view()), name='editar_solicitud'),
    path('solicitud/eliminar/<int:pk>', login_required(views.SolicitudDelete.as_view()), name='eliminar_solicitud')
]

apps/mascota/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from apps.mascota.views import (
    indexMascota,
    # mascotaNueva,
    # listarMascotas,
    # mascotaEditar,
    # mascotaEliminar,
    MascotaList,
    MascotaCreate,
    MascotaUpdate,
    MascotaDelete,
    WSMascotaList
)

app_name = 'mascota'

urlpatterns = [
    path('', indexMascota, name='mascota_index'),
    path('nueva',   login_required(MascotaCreate.as_view()), name='mascota_nueva'),
    path('listar', login_required(MascotaList.as_view()), name='listar_mascotas'),
    path('editar/<int:pk>',  login_required(MascotaUpdate.as_view()), name='editar_mascota'),
    path('eliminar/<int:pk>',  login_required(MascotaDelete.as_view()), name='eliminar_mascota'),
    path('ws/all', WSMascotaList, name='ws_all')
]

templates/tbases/base.html
{% load static i18n%}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="">

		<title>Refugio Animal</title>
		<!--Bootstrap CSS Link-->
		
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/starter-template.css' %}" rel="stylesheet">

		<title>{% block title %} Refugio {% endblock %}</title>
	</head>
<body>

	<!--NAVBAR-->
	{% block navbar %}
	<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
		<a class="navbar-brand" href="..">Inicio</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		
		<div class="collapse navbar-collapse">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false">Mascotas</a>
					<div class="dropdown-menu" aria-labelledby="dropdown01">
						<a class="dropdown-item" href="{% url 'mascota:listar_mascotas' %}">Listar</a>
						<a class="dropdown-item" href="{% url 'mascota:mascota_nueva' %}">Registrar</a>
						<!-- <a class="dropdown-item" href="#">Something else here</a> -->
					</div>
				</li>

				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false">Adopcion</a>
					<div class="dropdown-menu" aria-labelledby="dropdown01">
						<a class="dropdown-item" href="{% url 'adopcion:solicitud' %}">Solicitar</a>
						<a class="dropdown-item" href="{% url 'adopcion:listar_solicitud' %}">Listar solicitudes</a>
						<!-- <a class="dropdown-item" href="#">Something else here</a> -->
					</div>
				</li>
			</ul>

			<ul class="navbar-nav mr-right">
				<li class="nav-item">
					<a class="nav-link" href="http://codigofacilito.com">Codigo Facilito</a>
				</li>

				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="false">Opciones</a>
					<div class="dropdown-menu" aria-labelledby="dropdown01">
						<a class="dropdown-item" href="{% url "logout" %}">Salir</a>
					</div>
				</li>
			</ul>
		</div>
	</nav>
	{% endblock%}

	<!--CONTENIDO-->
	<main role="main" class="container">
		<div class="starter-template">
			{% block content %}
			<h5>Este es el bloque del contenido base</h5>
			{% endblock %}
		</div>
	</main>

	<!--FOOTER-->
	<div class="p-5">
		{% block footer %}
		{% endblock %}
	</div>

	<!--Bootstrap JavaScript-->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

	<!--{% block extrajs %}-->	
	<!--{% endblock %}-->	
</body>
</html>

templates/tbases/header.html
<header>Hola header</header>